"""add_is_free_to_users

Revision ID: b805f85120b2
Revises: ea5d2133f1e7
Create Date: 2026-03-18 21:16:07.776582+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b805f85120b2'
down_revision: Union[str, None] = 'ea5d2133f1e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('everapply_users', sa.Column('is_free', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('everapply_users', 'is_free')
    # ### end Alembic commands ###
