"""add_custom_ats_fields_to_users

Revision ID: b6be74883f3e
Revises: 2b26f307c79a
Create Date: 2026-03-23 06:09:19.410731+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6be74883f3e'
down_revision: Union[str, None] = '2b26f307c79a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('everapply_users', sa.Column('custom_ats_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('everapply_users', sa.Column('custom_ats_last_reset', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('everapply_users', 'custom_ats_last_reset')
    op.drop_column('everapply_users', 'custom_ats_count')
    # ### end Alembic commands ###
