"""add_scraping_enabled_to_user

Revision ID: 97e08b56b3e0
Revises: 3e9399cefdf9
Create Date: 2026-04-17 06:19:19.136165+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97e08b56b3e0'
down_revision: Union[str, None] = '3e9399cefdf9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('everapply_users', sa.Column('scraping_enabled', sa.Boolean(), nullable=False, server_default=sa.true()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('everapply_users', 'scraping_enabled')
    # ### end Alembic commands ###
