"""add_paid_at_to_users

Revision ID: 3e9399cefdf9
Revises: b6be74883f3e
Create Date: 2026-03-23 07:09:33.939547+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e9399cefdf9'
down_revision: Union[str, None] = 'b6be74883f3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('everapply_users', sa.Column('paid_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('everapply_users', 'paid_at')
    # ### end Alembic commands ###
