"""add_is_paid_to_users

Revision ID: ce090ac9b123
Revises: c1a2b3d4e5f6
Create Date: 2026-03-22 23:55:11.642793+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce090ac9b123'
down_revision: Union[str, None] = 'c1a2b3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('everapply_users', sa.Column('is_paid', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('everapply_users', 'is_paid')
    # ### end Alembic commands ###
